name: Publish Nuget Template

on:
  pull_request:
    types:
      - closed
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Update
        run: sudo apt update

      - name: Install xmllint & mono
        run: sudo apt install -y libxml2-utils mono-complete --fix-missing

      - uses: actions/checkout@v4
      
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Get version number from .nuspec
        id: version
        run: |
          VERSION=$(xmllint --xpath "string(//package/metadata/version)" Ravelaso.UiPath.Template.nuspec)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create package
        run: nuget pack Ravelaso.UiPath.Template.nuspec -version ${{ steps.version.outputs.version }}
      
      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: ravelaso

      - name: Publish package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{steps.login.outputs.NUGET_API_KEY}}
